# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®ã‚·ãƒ³ãƒœãƒ«ã‚’å¤‰æ›´
[character]
symbol = "â¯"

# Gitã‚»ã‚¯ã‚·ãƒ§ãƒ³ã®è¨­å®š
[git_branch]
symbol = "ğŸŒ± "

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸  ahead "
behind = "ğŸ¢ behind "
diverged = "ğŸ”€ diverged "
untracked = "ğŸ“ "
stashed = "ğŸ“¦ "
modified = "âœï¸ "
staged = "ğŸ—ƒï¸ "
renamed = "âœï¸ "
deleted = "ğŸ—‘ï¸ "

# Node.jsã‚»ã‚¯ã‚·ãƒ§ãƒ³ã®è¨­å®š
[nodejs]
symbol = "â¬¢ "

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªãƒ‘ã‚¹ã®çŸ­ç¸®è¡¨ç¤º
[directory]
truncation_length = 3
