
# ç¶™ç¶šãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®è¨­å®š
continuation_prompt = '[â¯â¯ ](fg:blue)'

# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®ã‚·ãƒ³ãƒœãƒ«ã‚’å¤‰æ›´
[character]
error_symbol = "[â¯â¯â¯](bold red)"
success_symbol = "[â¯â¯â¯](bold green)"

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªãƒ‘ã‚¹ã®çŸ­ç¸®è¡¨ç¤º
[directory]
style = "fg:blue"
format = "[$path]($style)"
truncation_length = 4
truncation_symbol = "..."
truncate_to_repo = false

# Gitã®å·®åˆ†ã®è¡¨ç¤º
[git_status]
style = "fg:blue"
format = '([\[$all_status$ahead_behind\]]($style))'

# Gitãƒ–ãƒ©ãƒ³ãƒã®è¡¨ç¤º
[git_branch]
format = " [$symbol $branch]($style)"
style = "fg:#888888"
symbol = "îœ¥"

# Gitã®å·®åˆ†ã®è¡¨ç¤º
[git_metrics]
disabled = false
added_style = 'bold blue'
format = '\([+$added]($added_style)/[-$deleted]($deleted_style)\)'
only_nonzero_diffs = true

# Node.jsã‚»ã‚¯ã‚·ãƒ§ãƒ³ã®è¨­å®š
[nodejs]
style = "#ffc0cb"
format = " [$symbol $version]($style)"
symbol = 'îœ˜'

# Pythonã‚»ã‚¯ã‚·ãƒ§ãƒ³ã®è¨­å®š
[python]
detect_extensions = ['py', 'ipynb']
pyenv_version_name = true
style = "yellow"
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

# Dockerã‚³ãƒ³ãƒ†ã‚­ã‚¹ãƒˆã‚»ã‚¯ã‚·ãƒ§ãƒ³ã®è¨­å®š
[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

# ã‚³ãƒãƒ³ãƒ‰å®Ÿè¡Œæ™‚é–“ã®è¡¨ç¤º
[cmd_duration]
show_milliseconds = true
format = ' [ó±«Œ $duration]($style)'
